add trusted-user-app to examples
gitcoinco/passport-scorer pull request #241
Opened 2023-05-10 13:50 UTC by jmcook1186

Adds a new demo app to the examples folder
The app is built with Nextjs and Chakra-UI

A user can connect and check whether they meet some arbitrary trust requirements combining a threshold Passport score and ownership of specific stamps.

The default trust criteria is: 
- Passport score > 20
- Owns a Lens stamp
- Owns a Github stamp

There is a checkbox that can be used to toggle rendering the complete list of the user's stamps

2023-06-02 14:25 UTC, 0xZakk requested changes

2023-06-02 14:25 UTC, 0xZakk commented on examples/check-trusted-user-app/app/api/hello/route.ts
> +export async function GET(request: Request) {
@jmcook1186 do we need this? It's just the hello next example

2023-06-02 14:25 UTC, 0xZakk commented on examples/check-trusted-user-app/app/page.tsx
> +'use client'
`page.tsx`, `page-backup.tsx`, and `boilerplate.tsx` all look very similar to me - are they copies of each other? Which one do we need?

2023-06-02 14:25 UTC, 0xZakk commented on examples/check-trusted-user-app/app/page.tsx
> +const APIKEY = process.env.NEXT_PUBLIC_GC_API_KEY
Can you add a sample `.env` file?

2023-06-02 14:25 UTC, 0xZakk commented on examples/check-trusted-user-app/README.md
> +npx create-next-app passport-app
These are the instructions for creating a new next.js app - shouldn't the steps here be to get this one up and running? So: npm install, npm run, etc

2023-06-02 14:25 UTC, 0xZakk commented on examples/check-trusted-user-app/README.md
> +npx create-next-app passport-app
Or do we want to have the tutorial here? I think my preference would be to keep these readme's pretty light and link to the tutorial in the docs (on gitbook)

2023-06-02 15:48 UTC, jmcook1186 commented on examples/check-trusted-user-app/app/api/hello/route.ts
> +export async function GET(request: Request) {
good point - deleting in next commit

2023-06-02 15:50 UTC, jmcook1186 commented on examples/check-trusted-user-app/app/page.tsx
> +'use client'
good point - I forgot to add `page-backup.tsx` to my .gitignore. 
The others are useful though - the tutorial basically takes someone from `boilerplate.tsx` as a starting point to `page.tsx` as a finishing point.

2023-06-02 15:55 UTC, jmcook1186 commented on examples/check-trusted-user-app/README.md
> +npx create-next-app passport-app
yea good point
Another option is to only include page.tsx here and instruct users to create-next-app, copy in page,tsx and then follow the tutorial for settign up their environment variables.

2023-06-05 10:31 UTC, jmcook1186 commented on examples/check-trusted-user-app/app/page.tsx
> +'use client'
`page-backup.tsx` deleted

2023-06-05 10:34 UTC, jmcook1186 commented on examples/check-trusted-user-app/app/page.tsx
> +const APIKEY = process.env.NEXT_PUBLIC_GC_API_KEY
done (`.env.local-example`)

2023-06-05 10:35 UTC, jmcook1186 commented
Hi @0xZakk 
removed the unnecessary files, updated the readme, added a .env.local-example.

2023-06-09 16:17 UTC, 0xZakk approved these changes

2023-06-09 16:17 UTC, merged