chore(api): adds initial acceptance test setup
gitcoinco/passport-scorer pull request #30
Opened 2022-12-16 07:52 UTC by aminah-io

2022-12-21 08:22 UTC, nutrina commented on api/scorer/test/test_create_community_id.py
> +    # community = Community.objects.all()[0]
Please also check the attributes (name & description) of the community instance

2022-12-21 08:35 UTC, nutrina requested changes
Just some minor observations
Please also add / update the cypress tests

2022-12-21 08:35 UTC, nutrina commented on api/scorer/test/test_create_community_id.py
> +    mocker.patch("account.views.submit_signed_challenge", return_value=scorer_account)
I don't think this mock is used

2022-12-21 08:35 UTC, nutrina commented on api/scorer/test/test_create_api_account.py
> +    assert len(Account.objects.all()) == 1
Please check the account address, it should match the account that signed the message

2022-12-21 08:35 UTC, nutrina commented on api/scorer/test/test_create_api_account.py
> +    return no_account_db_response
This is probably not needed, it does not seem to be used anywhere

2022-12-21 08:35 UTC, nutrina commented on api/scorer/test/test_create_api_keys.py
> +    mocker.patch("account.views.submit_signed_challenge", return_value=scorer_account)
Ido  not think we need this patch.

2023-01-09 20:52 UTC, schultztimothy approved these changes
This looks great 🚀 . From what I'm seeing the changes requested by @nutrina have been resolved, everything is passing and the requested tickets are covered.

2023-01-09 20:52 UTC, merged